env:
  browser: true
  es2021: true
  jest: true
  commonjs: true

extends:
  - 'plugin:react/recommended'
  - google

parserOptions:
  ecmaVersion: 12
  sourceType: module
  ecmaFeatures:
    jsx: true

plugins:
  - react

settings:
  react:
    version: detect

rules: {
  "indent": [2, 2]
}
