env:
  browser: true
  commonjs: true
  es2021: true
  jest: true

extends:
  - google

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 12

ignorePatterns:
  - "./client/"

plugins:
  - '@typescript-eslint'

rules: {
  "indent": [2, 2]
}
